# HTTP Server
server:
  address: ':8888'
  log-path: './logs/server'
  dump-router-map: true
  access-log-enabled: true
  error-log-enabled: true
  graceful: true

# Logger
logger:
  path: './logs/log'
  level: 'all'
  stdout: true

# database 配置
database:
  default: # 默认启动Mysql配置
    link: "mysql:root:willzhang@tcp(127.0.0.1:3306)/go_base_server"
    debug: true
  logger: # Database logger.
    path: './logs/sql'
    level: 'all'
    stdout: true
